/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef TYPES_ENDPOINT_GENERATED_H_
#define TYPES_ENDPOINT_GENERATED_H_

#ifdef UA_ENABLE_AMALGAMATION
#include "open62541.h"
#else
#include <open62541/types.h>
#include <open62541/types_generated.h>

#endif



_UA_BEGIN_DECLS


/**
 * Every type is assigned an index in an array containing the type descriptions.
 * These descriptions are used during type handling (copying, deletion,
 * binary encoding, ...). */
#define UA_TYPES_ENDPOINT_COUNT 3
extern UA_EXPORT const UA_DataType UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_COUNT];

/**
 * TSNApplicationEngineeringParameters
 * ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 */
typedef struct {
    UA_String commandedStatus;
    UA_String currentStatus;
    UA_Boolean sendReceiveEnabled;
    UA_UInt64 basetime;
    UA_Int32 qbvOffset;
    UA_String destinationMAC;
    UA_String subscribedMAC;
    UA_String interface;
    UA_Double cycleTime;
    UA_Int32 socketPriority;
    UA_UInt32 wCET;
} UA_TSNApplicationEngineeringParameters;

#define UA_TYPES_ENDPOINT_TSNAPPLICATIONENGINEERINGPARAMETERS 0

/**
 * TSNApplicationParameter
 * ^^^^^^^^^^^^^^^^^^^^^^^
 */
typedef struct {
    UA_String name;
    UA_String type;
    UA_String value;
} UA_TSNApplicationParameter;

#define UA_TYPES_ENDPOINT_TSNAPPLICATIONPARAMETER 1

/**
 * TSNApplication
 * ^^^^^^^^^^^^^^
 */
typedef struct {
    UA_String iD;
    UA_String path;
    size_t applicationParametersSize;
    UA_TSNApplicationParameter *applicationParameters;
    UA_TSNApplicationEngineeringParameters engineeringParameters;
} UA_TSNApplication;

#define UA_TYPES_ENDPOINT_TSNAPPLICATION 2


_UA_END_DECLS

#endif /* TYPES_ENDPOINT_GENERATED_H_ */
