/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#ifndef TYPES_ENDPOINT_GENERATED_HANDLING_H_
#define TYPES_ENDPOINT_GENERATED_HANDLING_H_

#include "types_endpoint_generated.h"

_UA_BEGIN_DECLS

#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
# pragma GCC diagnostic push
# pragma GCC diagnostic ignored "-Wmissing-field-initializers"
# pragma GCC diagnostic ignored "-Wmissing-braces"
#endif


/* TSNApplicationEngineeringParameters */
static UA_INLINE void
UA_TSNApplicationEngineeringParameters_init(UA_TSNApplicationEngineeringParameters *p) {
    memset(p, 0, sizeof(UA_TSNApplicationEngineeringParameters));
}

static UA_INLINE UA_TSNApplicationEngineeringParameters *
UA_TSNApplicationEngineeringParameters_new(void) {
    return (UA_TSNApplicationEngineeringParameters*)UA_new(&UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONENGINEERINGPARAMETERS]);
}

static UA_INLINE UA_StatusCode
UA_TSNApplicationEngineeringParameters_copy(const UA_TSNApplicationEngineeringParameters *src, UA_TSNApplicationEngineeringParameters *dst) {
    return UA_copy(src, dst, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONENGINEERINGPARAMETERS]);
}

UA_DEPRECATED static UA_INLINE void
UA_TSNApplicationEngineeringParameters_deleteMembers(UA_TSNApplicationEngineeringParameters *p) {
    UA_clear(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONENGINEERINGPARAMETERS]);
}

static UA_INLINE void
UA_TSNApplicationEngineeringParameters_clear(UA_TSNApplicationEngineeringParameters *p) {
    UA_clear(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONENGINEERINGPARAMETERS]);
}

static UA_INLINE void
UA_TSNApplicationEngineeringParameters_delete(UA_TSNApplicationEngineeringParameters *p) {
    UA_delete(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONENGINEERINGPARAMETERS]);
}

/* TSNApplicationParameter */
static UA_INLINE void
UA_TSNApplicationParameter_init(UA_TSNApplicationParameter *p) {
    memset(p, 0, sizeof(UA_TSNApplicationParameter));
}

static UA_INLINE UA_TSNApplicationParameter *
UA_TSNApplicationParameter_new(void) {
    return (UA_TSNApplicationParameter*)UA_new(&UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONPARAMETER]);
}

static UA_INLINE UA_StatusCode
UA_TSNApplicationParameter_copy(const UA_TSNApplicationParameter *src, UA_TSNApplicationParameter *dst) {
    return UA_copy(src, dst, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONPARAMETER]);
}

UA_DEPRECATED static UA_INLINE void
UA_TSNApplicationParameter_deleteMembers(UA_TSNApplicationParameter *p) {
    UA_clear(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONPARAMETER]);
}

static UA_INLINE void
UA_TSNApplicationParameter_clear(UA_TSNApplicationParameter *p) {
    UA_clear(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONPARAMETER]);
}

static UA_INLINE void
UA_TSNApplicationParameter_delete(UA_TSNApplicationParameter *p) {
    UA_delete(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONPARAMETER]);
}

/* TSNApplication */
static UA_INLINE void
UA_TSNApplication_init(UA_TSNApplication *p) {
    memset(p, 0, sizeof(UA_TSNApplication));
}

static UA_INLINE UA_TSNApplication *
UA_TSNApplication_new(void) {
    return (UA_TSNApplication*)UA_new(&UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATION]);
}

static UA_INLINE UA_StatusCode
UA_TSNApplication_copy(const UA_TSNApplication *src, UA_TSNApplication *dst) {
    return UA_copy(src, dst, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATION]);
}

UA_DEPRECATED static UA_INLINE void
UA_TSNApplication_deleteMembers(UA_TSNApplication *p) {
    UA_clear(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATION]);
}

static UA_INLINE void
UA_TSNApplication_clear(UA_TSNApplication *p) {
    UA_clear(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATION]);
}

static UA_INLINE void
UA_TSNApplication_delete(UA_TSNApplication *p) {
    UA_delete(p, &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATION]);
}

#if defined(__GNUC__) && __GNUC__ >= 4 && __GNUC_MINOR__ >= 6
# pragma GCC diagnostic pop
#endif

_UA_END_DECLS

#endif /* TYPES_ENDPOINT_GENERATED_HANDLING_H_ */
