/**********************************
 * Autogenerated -- do not modify *
 **********************************/

#include "types_endpoint_generated.h"

/* TSNApplicationEngineeringParameters */
static UA_DataTypeMember TSNApplicationEngineeringParameters_members[11] = {
{
    UA_TYPENAME("CommandedStatus") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("CurrentStatus") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, currentStatus) - offsetof(UA_TSNApplicationEngineeringParameters, commandedStatus) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("SendReceiveEnabled") /* .memberName */
    &UA_TYPES[UA_TYPES_BOOLEAN], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, sendReceiveEnabled) - offsetof(UA_TSNApplicationEngineeringParameters, currentStatus) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Basetime") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT64], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, basetime) - offsetof(UA_TSNApplicationEngineeringParameters, sendReceiveEnabled) - sizeof(UA_Boolean), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("QbvOffset") /* .memberName */
    &UA_TYPES[UA_TYPES_INT32], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, qbvOffset) - offsetof(UA_TSNApplicationEngineeringParameters, basetime) - sizeof(UA_UInt64), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("DestinationMAC") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, destinationMAC) - offsetof(UA_TSNApplicationEngineeringParameters, qbvOffset) - sizeof(UA_Int32), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("SubscribedMAC") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, subscribedMAC) - offsetof(UA_TSNApplicationEngineeringParameters, destinationMAC) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Interface") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, interface) - offsetof(UA_TSNApplicationEngineeringParameters, subscribedMAC) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("CycleTime") /* .memberName */
    &UA_TYPES[UA_TYPES_DOUBLE], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, cycleTime) - offsetof(UA_TSNApplicationEngineeringParameters, interface) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("SocketPriority") /* .memberName */
    &UA_TYPES[UA_TYPES_INT32], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, socketPriority) - offsetof(UA_TSNApplicationEngineeringParameters, cycleTime) - sizeof(UA_Double), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("WCET") /* .memberName */
    &UA_TYPES[UA_TYPES_UINT32], /* .memberType */
    offsetof(UA_TSNApplicationEngineeringParameters, wCET) - offsetof(UA_TSNApplicationEngineeringParameters, socketPriority) - sizeof(UA_Int32), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* TSNApplicationParameter */
static UA_DataTypeMember TSNApplicationParameter_members[3] = {
{
    UA_TYPENAME("Name") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Type") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_TSNApplicationParameter, type) - offsetof(UA_TSNApplicationParameter, name) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Value") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_TSNApplicationParameter, value) - offsetof(UA_TSNApplicationParameter, type) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};

/* TSNApplication */
static UA_DataTypeMember TSNApplication_members[4] = {
{
    UA_TYPENAME("ID") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    0, /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("Path") /* .memberName */
    &UA_TYPES[UA_TYPES_STRING], /* .memberType */
    offsetof(UA_TSNApplication, path) - offsetof(UA_TSNApplication, iD) - sizeof(UA_String), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("ApplicationParameters") /* .memberName */
    &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONPARAMETER], /* .memberType */
    offsetof(UA_TSNApplication, applicationParametersSize) - offsetof(UA_TSNApplication, path) - sizeof(UA_String), /* .padding */
    true, /* .isArray */
    false  /* .isOptional */
},
{
    UA_TYPENAME("EngineeringParameters") /* .memberName */
    &UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_TSNAPPLICATIONENGINEERINGPARAMETERS], /* .memberType */
    offsetof(UA_TSNApplication, engineeringParameters) - offsetof(UA_TSNApplication, applicationParameters) - sizeof(void *), /* .padding */
    false, /* .isArray */
    false  /* .isOptional */
},};
const UA_DataType UA_TYPES_ENDPOINT[UA_TYPES_ENDPOINT_COUNT] = {
/* TSNApplicationEngineeringParameters */
{
    UA_TYPENAME("TSNApplicationEngineeringParameters") /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {3004LU}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {5001LU}}, /* .binaryEncodingId */
    sizeof(UA_TSNApplicationEngineeringParameters), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    11, /* .membersSize */
    TSNApplicationEngineeringParameters_members  /* .members */
},
/* TSNApplicationParameter */
{
    UA_TYPENAME("TSNApplicationParameter") /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {3008LU}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {5004LU}}, /* .binaryEncodingId */
    sizeof(UA_TSNApplicationParameter), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    3, /* .membersSize */
    TSNApplicationParameter_members  /* .members */
},
/* TSNApplication */
{
    UA_TYPENAME("TSNApplication") /* .typeName */
    {2, UA_NODEIDTYPE_NUMERIC, {3005LU}}, /* .typeId */
    {2, UA_NODEIDTYPE_NUMERIC, {5007LU}}, /* .binaryEncodingId */
    sizeof(UA_TSNApplication), /* .memSize */
    UA_DATATYPEKIND_STRUCTURE, /* .typeKind */
    false, /* .pointerFree */
    false, /* .overlayable */
    4, /* .membersSize */
    TSNApplication_members  /* .members */
},
};

